name: cat
favicon: null
layout_spectrum: 0.23086596536450088
typography_spectrum: 0.6534245649818331
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.07945207227021456
  lightness: 0.4334972435608506
  saturation: 0.791362150805071
  rhythmicContrast: 0.18352103512734175
purpose: []
